### ISSUE TITLE
LaTeX math support

### ISSUE THREAD

**Issue by EllBock** [c3er/mdview#13]
Hi, I would like to propose LaTeX math support that is usually done with MathJax by other note taking apps. As an engineering student I need to render a lot of formulas, and this is the only feature that I really miss in this fantastic app.

There are also other "extensions" that other note taking apps provide that you may want to implement later on, like
* Mermaid Diagrams
* MultiMarkdown Tables
* Emojis
* others listed in the [Joplin Markdown Guide](https://joplinapp.org/markdown/)

Hopefully these would not add too much complexity. 

Thank you for your hard work!

**Comment by c3er** [comment]
Hi, thanks for the feature request!

> Hopefully these would not add too much complexity.

It should be fairly easy to integrate these features in the current architecture. But it will still take some weeks to implement them, since it is only a spare time hobby project of mine.

**Comment by c3er** [comment]
It took a while but I implemented now most of the features from [the `markdown-it` demo](https://markdown-it.github.io/).

But I did not implement these features:

- **Mermaid Diagrams:** Would be really nice, but when I tried to include the plugin, my application did not start somehow. I didn't took the time to investigate this.
- **MultiMarkdown Tables:** Actually, I kind of forgot to implement this feature before uploading [the new release](https://github.com/c3er/mdview/releases/tag/v1.6.0). But the app supports HTML tables without any problems if someone needs complex table layouts. If you (or someone else) really want this feature, I'll add this.

LaTeX math support is now included, so I close this issue. If you encounter some problems with rendering certain formulas, please open a new issue.

See [release 1.6.0](https://github.com/c3er/mdview/releases/tag/v1.6.0)
