### ISSUE TITLE
Option to install mdview silently / unattended

### ISSUE THREAD

**Issue by thmmsn** [c3er/mdview#15]
Can install mdview silently `mdview.setup<version>.exe /S`, but can't find an option for system wide installation.

**Comment by c3er** [comment]
Thanks for filing this issue!

I have only little time right now, so it will take at least some days until I can take a deeper look.

**Comment by c3er** [comment]
I added in the README [a section about the Windows installer](https://github.com/c3er/mdview#windows), containing the parameter for silent installation.

Feel free to reopen this issue, if you expected another solution.
