### ISSUE TITLE
Feature request: make line breaks configurable

### ISSUE THREAD

**Issue by ilog2000** [c3er/mdview#16]
Hello,

Markdown-it has an option **breaks** that is _false_ by default. See the details [here](https://markdown-it.github.io/markdown-it/#MarkdownIt.new). I prefer to have it _true_, and rebuild the app for my needs every time. Would you mind to make this option configurable? Thank you.

**Comment by c3er** [comment]
Thanks for filing this issue!

I propose following implementation:

- A menu entry "View" --> "Convert line breaks \n" with a checked state that defaults to *false*
- This setting will be saved application wide, i.e. independent from the document

Do you agree with this proposal?

Later, I may add additional switches to turn on or off certain Markdown rendering features. The line-breaks option would go with the the other options in an own sub menu under "View".

**Comment by ilog2000** [comment]
Sure, no objections, a good solution.

**Comment by c3er** [comment]
A [new release](https://github.com/c3er/mdview/releases/tag/v2.3.0) with the requested feature and some additional Markdown configuration options is out.

![Screenshot of Markdown rendering options](https://user-images.githubusercontent.com/24460532/144025549-78f8fec5-5e95-4b4a-a9a0-0689627b2ad5.png)

If you encounter some problems with the rendering configuration, it seems the best, if you open a new issue, explaining that problem.
