### ISSUE TITLE
Support for Task lists/Checklists missing

### ISSUE THREAD

**Issue by wasu-code** [c3er/mdview#19]
I noticed mdview do not support displaying checklists, that are extremaly useful in some cases.

[Task lists](https://www.markdownguide.org/extended-syntax/#task-lists)/Checklists are made with the following structure:
```
- [ ] unchecked item
- [x] checked item
```
and give the following output:  
- [ ] unchecked item
- [x] checked item

markdown-it doesn't support it itself but some community-written plugins are available [npmjs.com : lists](https://www.npmjs.com/search?q=keywords%3Amarkdown-it-plugin%20task)

<sub>Thank you for your hard work.</sub>

**Comment by c3er** [comment]
Thanks for filing the issue!

This seems not too hard, so a new release, containing this feature, may come soon. Though I don't want to promise too much.

**Comment by c3er** [comment]
I just published [a new release](https://github.com/c3er/mdview/releases/tag/v2.4.0), containing your feature request.

You can check and uncheck each checkbox. But if you want to persist the check state, you have to edit the document itself.
