### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by svrana** [c3er/mdview#2]
Love to see the render refresh as the file is saved.

**Comment by c3er** [comment]
I didn't consider this feature yet, since mdview is explicitly no editor but just a viewer. But I will add it in the next release.

**Comment by c3er** [comment]
Released [version 1.3.0](https://github.com/c3er/mdview/releases/tag/v1.3.0).

It seems the best, to open a new issue, containing the exact steps to reproduce, if you encounter problems with this feature.
