### ISSUE TITLE
REQUEST: Can you please make the rendering not dependent of file extension [right now only renders properly files with .md and .markdown extensions]

### ISSUE THREAD

**Issue by j2oc** [c3er/mdview#20]
First of all thank you for this.

I searched far and wide for a Markdown Viewer-only for some time now. There are but a few and almost all fall short of delivering the bare minimum acceptable functionality.

When I first embarked in that quest it seemed a fairly easy proposition: find an Markdown Reader- or Viewer-only for those files that are not to be edited because they represent a final, storable record of a Text-based work . Articles, essays and other writings authored by me or others that are not to be accidentally "corrupted" by me opening it in a Editor and, by mistake or lack of attention, unintentionally saving it with some edits (probably, I dare to venture it, this same rationale counted towards you own motivation to build this).

This is almost an Egg of Columbus kind of thing: pretty obvious in hindsight while not quite so much before. Or at least that is the most logical explanation I can summon for having found so few Viewers -- and of subpar quality -- while Editors (of increasingly good quality) seem to abound and prosper.

I was already contemplating rolling out my own when I, luckily, managed to serendipitously bump into mdview.

It does exactly what it says in the box (so to speak) and was quite elated when I tested with a handful of .md files I had just lying about.

However the feeling quickly subsided when I tried the Markdown files I described above (the final, non-editable, read-only ones), which, for convenience and to keep them visibly/clearly differentiated and differentiable from the others, have a different extension from the ones I mentioned in the title (which seem to be the only ones that trigger the rendering from the markup into the intended presentation format).

When I tried with those it only presented me back with the Text version of it (as if opened by any regular Text Editor/Viewer). Not the formatted one I was expecting and hoping for,

And so. 

My request is: can you, please, kindly consider, in your next development cycle, to make this tool a more universal one, by giving more power and control back to the user -- by letting her/him decide which files can contain Markdown content (in other words, make it ignore the extension completely and try to render it as if the input was Markdown, regardless)?

Thank you so much.

**Comment by c3er** [comment]
Thanks for filing the issue!

I propose implementing following menu items in the "View" menu:

- **✔ Render this file as Markdown** The currently displayed file will be rendered as a markdown file, regardless of its file extension. The tool will remember this for that particular file.
- **✔ Render all ".xyz" files as Markdown** All files with the file extension ".xyz" will be rendered as Markdown. The tool will remember this decision. This menu item will always reflect the found extension of the currently opened file.

Would this implementation be OK?

---

Rationale behind the current implementation: It can happen that a source code file is linked in the Markdown document. The easiest approach to this would be to let the operating system open the file with its associated application. But in my experience, this is often not optimal, so I decided to open every non Markdown text file into the tool itself, which is for my workflow the best thing.

> Articles, essays and other writings authored by me or others that are not to be accidentally "corrupted" by me opening it in a Editor and, by mistake or lack of attention, unintentionally saving it with some edits (probably, I dare to venture it, this same rationale counted towards you own motivation to build this).

My rationale was simply to be able to double click a Markdown file in the file manager and let it open in a rendered form. The only thing that I knew about were browser plugins, but:

- I don't want to open everything in the browser window
- the plugin didn't had (or has) UTF-8 as default encoding, which gets annoying quite fast with non English texts.

Before that, I used VS Code to look into Markdown files (which I use up to today for authoring them) but it is a little cumbersome for just looking into READMEs and such.

**Comment by j2oc** [comment]
I see... I understand the predicament/conundrum: a way is needed to keep track of which files/formats (meaning: extensions and/or a particular file or files) are to be rendered (Markdown) in opposition to all the rest (Text, by default) that are not.

And, because of that, I have no objection whatsoever to your proposed whitelist-type solution.

Regarding the use cases you described as part of your motivation, I can totally relate. It also happens/happened to me. There is (should be) no need to launch a browser tab/window just to quickly read something local, much in the same way there is (should be) no reason to use a full-blown, full-featured Editor to do the same. Talk about overkill... That's what has taken me a little aback when I started looking. Probably my error was to, somewhat, equate a Markdown file to a PDF file, in my mind: the Reader/Viewer to Editor ratio tilts heavily into the Reader/Viewer corner, in the PDF case. The truth is a Markdown file seems to be somewhere, in a spectrum, between a "pure" Text file (i.e., one with no markup) and a PDF file -- while still being a Text file, per se. I think that might explain my (initial) dissonance.

I also sympathize/empathize with your referenced (non-) UTF-8 related woes (also felt them) and I also happen to agree (also by means of experience) with your assertion that opening a source code file from a link should not be done by the associated application.

And, again.

Thank you so very much.

**Comment by c3er** [comment]
Feature is now implemented in the `master` branch. A new release shouldn't take too long from now. It took quite a while and was also not easy to implement.

I leave this issue open until the new release is out.

**Comment by j2oc** [comment]
I imagined as much (re: difficulty).

Thank you again for your work.

**Comment by c3er** [comment]
[Version 2.5.0](https://github.com/c3er/mdview/releases/tag/v2.5.0) with your requested feature is now released.

**Comment by j2oc** [comment]
Thank you so much for following through on this.

Highly appreciated.
