### ISSUE TITLE
Embedded base64 encoded image not supported?

### ISSUE THREAD

**Issue by xCaradhras** [c3er/mdview#23]
Hello,

I tried to use this tool with embedded image. On other tools/viewers it works, but not here. :/

Am I doing something wrong?
Sample code: [bla.md](https://github.com/c3er/mdview/files/9855492/bla.md)

Could you look into this?
Best regards

**Comment by c3er** [comment]
Thanks for filing this issue!

After a very quick look, I don't see anything "wrong" with this file. Embedding images as data string was not considered as use case yet. Probably the tool messes something up while trying to render it or a step is missing before the image can be rendered.

I will take a deeper look.

**Comment by xCaradhras** [comment]
Thanks! I would love to offer my support, but my JS skills are practically non-existent. 😅 If I can help in any other way, feel free.

**Comment by c3er** [comment]
I just released [version 2.5.1](https://github.com/c3er/mdview/releases/tag/v2.5.1) that can now render embedded images.

The tool actually messed up the data URL. Preventing the tool from messing up this URL was enough to fix the bug.

Don't hesitate to file another issue, if you find some other bug or weird behavior or if you wish a feature!

**Comment by xCaradhras** [comment]
Thanks for adressing this issue so quickly 😊
