### ISSUE TITLE
Want the Table of Content

### ISSUE THREAD

**Issue by fireflyoo** [c3er/mdview#25]
Lack the function of TOC(Table of Content).

**Comment by c3er** [comment]
Thanks for filing this issue!

What do you mean? An outline feature like it is offered by VS Code?

![Screenshot of VS Code MD outline feature](https://user-images.githubusercontent.com/24460532/212091452-8c8acc93-5bf7-440d-9846-f40784c5969f.png)

Please be aware that I won't add any feature to the app that changes the opened file itself, i.e. adding a TOC to the opened file.

If you want an outline, e.g. as a sub window or sidebar or something like that, then I'll see when I find time for implementing this feature.

**Comment by fireflyoo** [comment]
> 

Yes ,  Like the outline feature by VSCode

**Comment by c3er** [comment]
Thanks for the clarification!

Maybe I'm able to implement this feature soon but I won't promise anything.

**Comment by c3er** [comment]
Short update: this feature is actually not trivial and takes some time. Parts are implemented but it is currently far from usable.

<img width="985" alt="Screenshot of Markdown viewer with TOC" src="https://user-images.githubusercontent.com/24460532/221957098-73e1a5df-8243-42aa-bc9e-ee6e48df5aa2.png">

**Comment by fireflyoo** [comment]
Amazing! I can't wait to try..

**Comment by c3er** [comment]
It took a whole while and made actually more work than the first version of the whole application😆

The buttons may currently not looking good -- see issue #29. But I don't want to let you wait even longer and just released [version 2.6.0](https://github.com/c3er/mdview/releases/tag/v2.6.0) with the new feature.

The TOC is hidden by default. It can be displayed via entries in the "View" menu or by pressing Alt+C (Option+C on macOS) for a single document only or via Alt+Shift+C (Option+Shift+C on macOS) for all documents.

Feel free to open a new issue, if you encounter a problem with this TOC feature or with anything else in the application or if you wish another feature.
