### ISSUE TITLE
Markdown with oversized table is not printed correctly

### ISSUE THREAD

**Issue by xCaradhras** [c3er/mdview#26]
Hello,

If you export a markdown to PDF via printing which contains a very large table, the table is cropped incorrectly:
![grafik](https://user-images.githubusercontent.com/19254772/220891698-fd45f531-26bb-43c1-a589-89a6db735289.png)
This is an example from a PDF that was created through a md file with a very large table. 
Hint: The scrollbar seems to be an image or something? The column to the right is cropped. 
Expectation: Everything is resized so it all fits into a page.

Can you please look into this? 

Best regards
Caradhras

**Comment by c3er** [comment]
Thanks for filing this issue!

Question about the expected resizing: Do you want the font to be scaled down, so that the table fits into the page? If not, how should the resize look like?

I'll look into this bug. But I think, solving this bug is either trivial (like changing one line at the right place) or very hard😅

The scrollbar is probably some remnant of the rendering. The rendered Markdown "webpage" is just sent to the printer driver without any change, besides of some CSS specifics for printed content:

```css
@media print {
    /* A few rules for rendering on "paper" */
}
```

**Comment by xCaradhras** [comment]
As long as I can read everything it is fine I guess :D
So, probably scaling everything down would probably the best option, so the structure of the table is preserved.

**Comment by c3er** [comment]
@xCaradhras Your table that doesn't fit contains very wide words, right? I want just be sure that I work on the "right" problem. See below for the test table I just created:

| Header                                        | Header                                        | Header                                        | Header                                        |
| --------------------------------------------- | --------------------------------------------- | --------------------------------------------- | --------------------------------------------- |
| VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable |
| VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable |
| VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable | VeryWideSingleWordToShowRenderingOfAWideTable |

**Comment by c3er** [comment]
A solution that would be easy to implement would look like on paper (or PDF):

![Screenshot of wide table in PDF](https://user-images.githubusercontent.com/24460532/221323363-6b5a1f90-0c8b-4ca1-a7b6-67bd2a6293ae.png)

Does this satisfy you?

**Comment by xCaradhras** [comment]
Hi, sorry, I was on vacation. Not perfect, but looks a lot better, sample:
![grafik](https://user-images.githubusercontent.com/19254772/235523293-a9aeb4af-c239-4980-9193-1ce6af986923.png)
If you would be able to remove the unnecessary line breaks in the first three colums, the result would be perfect! Or does it result from my MD?

Another thing that I saw during testing: If you print the file with "Microsoft Print to PDF", the initial file name is empty. Can you provide the original files name (of the md) as initial suggestion?

**Comment by c3er** [comment]
Thanks, @xCaradhras!

I'll see, what I can do. Could you attach some Markdown samples with tables, that don't look good? It could help to have the actual syntax for these tables availbale.

I reopen this issue and let it open  until your example is rendered properly.

**Comment by xCaradhras** [comment]
Hello,
here you go.
[sample.md](https://github.com/c3er/mdview/files/11396150/sample.md)
[sample.PDF](https://github.com/c3er/mdview/files/11396151/sample.PDF)

**Comment by c3er** [comment]
I hope, [version 2.6.1](https://github.com/c3er/mdview/releases/tag/v2.6.1) prints now tables properly. Your sample looked good on my machine^^ Feel free to reopen this issue, if tables are still not printed properly.

**Comment by xCaradhras** [comment]
Thank you! I will test tomorrow :)
