### ISSUE TITLE
Use graphics for butons in Table of Content

### ISSUE THREAD

**Issue by c3er** [c3er/mdview#29]
Currently, UTF-8 symbols are used for the buttons in the TOC. But the appearance of them is depended on the OS and the current default sans-serif font. Instead the buttons should consist of actual graphics that appear identical on al platforms.

Current state:

![Screenshot of TOC with ugly buttons](https://user-images.githubusercontent.com/24460532/231584762-eec41980-b84f-4f07-b14d-4f6ac7cdf373.png)

**Comment by xCaradhras** [comment]
Very nice feature! Just tested 2.6.0, one other possible improvement for TOC: The readability in dark mode can be improved:
![grafik](https://user-images.githubusercontent.com/19254772/235520728-14059ff7-b46f-4384-adbd-8898f4419932.png)

Thank you!

**Comment by c3er** [comment]
Thanks, @xCaradhras!

Though I noticed and [fixed](https://github.com/c3er/mdview/commit/6220f52407926602e2769cdb7f540d0aabfb6962) the TOC color problem already. I will release a version 2.6.1 after I fixed this issue here (maybe also containing your feedback in #26 if the solution is not too complicated).
