### ISSUE TITLE
No focus on content by default

### ISSUE THREAD

**Issue by ilog2000** [c3er/mdview#31]
Hello!
I just moved from v2.5.1 to v2.6.1 and noticed that content does not get focus by default. Previously I was able to press Page Down key right after opening a file and see the next block of content. New version does not react to Page Down until I click somewhere on the content with mouse. Of course, this is minor thing, but hopefully easy to fix.

**Comment by c3er** [comment]
[Version 2.6.2](https://github.com/c3er/mdview/releases/tag/v2.6.2) contains now the fix to this issue.

Feel free to open another issue🙂

If you observe, that the application does "sometimes" not react to keyboard presses, then this issue was not fixed properly and you could reopen it.
