### ISSUE TITLE
Remove minimum window width

### ISSUE THREAD

**Issue by wasu-code** [c3er/mdview#33]
### What changed

In previous versions (like 2.4.0) I was able to resize window however I liked, making it even as thin as 161px.   
Now it is **impossible to make it thinner than 609px**.  

### Why is it important

I am used to split my desktop in 3 windows: middle one (browser or MS Teams) is the biggest and those on the sides (mdview and notepad) are small and used to make notes. It just make it easier to organize your workspace when there is no minimum width limitation.

---

PS. I am not sure if it's something that can be easily changed but I would really appreciate it.  
And as always: Thanks for your hard work 🙏

**Comment by c3er** [comment]
Thanks for filing this issue!

I won't remove the minimum window width (and height). But obviously, my chosen minimum values are too big. I will make it possible to resize the window to much smaller dimensions.

My reasoning implementing the minimum window dimensions:

1. During implementing the table-of-content feature, I felled that the this is the minimum size, where the application can still be used properly with activated sidebar.
2. In previous versions, it was possible to resize the window to like 1x1 pixel (maybe some more pixels). If this happens, it's sometimes not easy to even spot where on the desktop the window is. If not anything, then the window controls should at least be reachable.

**Comment by c3er** [comment]
[Version 2.7.0](https://github.com/c3er/mdview/releases/tag/v2.7.0), containing the decreased minimum, sizes is now released.

Feel free to reopen the issue, if the chosen values are still too big.
