### ISSUE TITLE
Suggestion: Search function

### ISSUE THREAD

**Issue by xCaradhras** [c3er/mdview#34]
Hello,

first kudos for the development of the app and the responsiveness. :)

What about a search function? 😀

Best regards!

**Comment by c3er** [comment]
Thanks again for filing this issue!🙂

Up to now, it was no requirement -- neither by me nor was were an issue filed. But now, there is a reason to implement this.

> first kudos for the development of the app and the responsiveness. :)

Thanks! Well, I don't like it to file an issue to a project and don't getting any kind of response even after months or years. How long it takes to implement or fix something is another question but in my opinion, a maintainer should at least give some kind of reaction not too long after the issue creation.

**Comment by c3er** [comment]
[Version 2.8.0](https://github.com/c3er/mdview/releases/tag/v2.8.0) contains now the search function.
