### ISSUE TITLE
Suggestion: Provide Checksum File(s) for Releases

### ISSUE THREAD

**Issue by sid-the-sloth** [c3er/mdview#35]
It would be good to have a checksum file for all binaries released, or individual checksum files for each binary.

A good example can be seen by checking VSCodium project. Thanks!

**Comment by c3er** [comment]
Thanks for filing this issue!

I'll see that the checksum files are added beginning with the next release. This issue will stay open until this release.

**Comment by c3er** [comment]
The [release 2.8.0](https://github.com/c3er/mdview/releases/tag/v2.8.0) provides now a checksum file for each artifact.

**Comment by sid-the-sloth** [comment]
> The [release 2.8.0](https://github.com/c3er/mdview/releases/tag/v2.8.0) provides now a checksum file for each artifact.

Thank you for doing this! Works great.
