### ISSUE TITLE
Suggestion: Option to hide YAML header

### ISSUE THREAD

**Issue by irosyadi** [c3er/mdview#37]
Hello Christ,

This is not really an issue. Since many markdown editors support the YAML header, is it possible to add an option to hide the header in MDView?

Huge thanks

**Comment by c3er** [comment]
Hi, thanks for filing this issue!

I'll see that the next release contains this feature.

**Comment by c3er** [comment]
[Version 3.0.0](https://github.com/c3er/mdview/releases/tag/v3.0.0) does now render Markdown headers properly. As wished, it is also possible to hide the header. You find the option for this in the settings dialog.
