### ISSUE TITLE
'Encodings' option request

### ISSUE THREAD

**Issue by yozhic** [c3er/mdview#4]
[mdview of UTF-16 LE file](https://funkyimg.com/i/35K4P.png)
This is what UTF16-LE encoded file looks like. It might be a good idea to add an option to select an encoding :-)

**Comment by c3er** [comment]
I made 2 other issues to implement after this one. I'll see whether I'll make a release right after implementing your feature request or after implementing #5 and/or #6.

**Comment by c3er** [comment]
I released [version 1.4.0](https://github.com/c3er/mdview/releases/tag/v1.4.0).
