### ISSUE TITLE
Feature Request: Drag & Drop support

### ISSUE THREAD

**Issue by xCaradhras** [c3er/mdview#40]
Hello :)

as requested in #39 here my feature request as a separate thread / issue:

1. drag & drop support 
2. a preference for "open in new instance" vs "reuse instance" vs "ask what to do" would be nice.

Thanks and best regards

**Comment by c3er** [comment]
[Version 3.0.0](https://github.com/c3er/mdview/releases/tag/v3.0.0) does now support drag & drop for all text files.

Also, the preference, you wished for, is also implemented. As dialog that opens at dropping and as an option in the settings dialog.

Enjoy and don't hesitate to file other problems and missing features!
