### ISSUE TITLE
Feature Request: Recently opened files

### ISSUE THREAD

**Issue by xCaradhras** [c3er/mdview#41]
Hello :)

as requested in #39 here my feature request as a separate thread / issue:

A menu for reciently opened files. 

Thanks and best regards :)

**Comment by c3er** [comment]
Thanks

**Comment by c3er** [comment]
[Version 3.0.0](https://github.com/c3er/mdview/releases/tag/v3.0.0) lists now the recently opened files in the File menu. You can set the count of this list in the settings dialog.

Enjoy!
