### ISSUE TITLE
displaying local image file

### ISSUE THREAD

**Issue by markp999** [c3er/mdview#52]
I'm in the (very) early stages of designing a standalone bookmark viewer (not a manager, not an editor, not tied to a specific browser) and _mdview_ is perfect for my needs.

One issue I'm having is trying to use local image files.  _mdview_ is displaying them as the generic broken link/image.

I have been successful in converting image files to base64 and _mdview_ **does** display the base64 image as expected.

Before I jump through the hoops to convert all image files to base64 I'm trying to find out if there's something I'm doing wrong or if I've run up against a limit of _mdview_.

My sample: [sample.md](https://github.com/c3er/mdview/files/15214918/sample.md)

NOTE: If I change the file extension to _.html_ and load into my browser then all images (base64, local file) display properly.

Thanks,
Mark

**Comment by c3er** [comment]
Thanks for filing this issue!

I could reproduce this problem, though next time, it would be better to provide me a ZIP package, containing the images.

The problem is, that the tool doesn't regard absolute file paths at all. This is also not recommended. Using a relative path (i.e. just `stackoverflow.com.png` instead of `file://C:/Users/myuser/Desktop/stackoverflow.com.png`, assuming that the `sample.md` is also on your Desktop) works without problems.

But I consider this still a bug and I hope, that I can release a bugfix release this week. But I won't promise this time frame.

**Comment by c3er** [comment]
> I'm in the (very) early stages of designing a standalone bookmark viewer (not a manager, not an editor, not tied to a specific browser) and mdview is perfect for my needs.

Interesting😂👍

**Comment by markp999** [comment]
> I could reproduce this problem, though next time, it would be better to provide me a ZIP package, containing the images.

will do

> The problem is, that the tool doesn't regard absolute file paths at all. This is also not recommended. Using a relative path (i.e. just `stackoverflow.com.png` instead of `file://C:/Users/myuser/Desktop/stackoverflow.com.png`, assuming that the `sample.md` is also on your Desktop) works without problems.

Yeah, at some point I'll address the absolute vs relative path argument but in the meantime I'm just trying to get the html/markdown to work (I'm a html/markdown newbie).

I'm looking at 100's of image files so the final design will be looking to access the image files from somewhere other than the desktop.

General question re: _mdview_ and relative paths ... does _mdview_ have a hardcoded/default start directory from which relative paths are derived ... or does _mdview_ use the startup directory (eg, `cd C:\some\other\dir; mdview`) to derive relative paths?

**Comment by c3er** [comment]
The [new version](https://github.com/c3er/mdview/releases/tag/v3.1.1), that now handles absolute paths properly, is just released. Enjoy!

**Comment by markp999** [comment]
I've verified my test cases (relative and absolute paths) are working as desired.

Thanks for the quick update!
