### ISSUE TITLE
Feature request: MSI install package

### ISSUE THREAD

**Issue by thmmsn** [c3er/mdview#53]
As title says.

I'm requesting an MSI package for easy deployment of mdview with Intune.

**Comment by c3er** [comment]
Thanks for filing this issue!

I'll see whether I can provide an MSI package with the next release.

**Comment by c3er** [comment]
I just released [a new version](https://github.com/c3er/mdview/releases/tag/v3.1.1), that now also has [an MSI package](https://github.com/c3er/mdview/releases/download/v3.1.1/mdview-3.1.1-x64.msi). Enjoy!

If you encounter any problems with this MSI package, then it seems the best to open a new issue, describing that problem.
