### ISSUE TITLE
Inconsistent Hyperlink handling

### ISSUE THREAD

**Issue by BigAlUK99** [c3er/mdview#55]
It would be extremely helpful if the hyperlink handling were more capable of handling hyperlinks created using Typora.  This is especially true for local relative links to open files or start applications.

**Comment by c3er** [comment]
Also, to be able to open local, arbitrary files via Markdown Viewer is important for myself and therefore supported basically since the beginning. I'm wondering, which case (or cases) are not handled properly.

**Comment by c3er** [comment]
I'm closing this, because I have no idea, what to do. Feel free to reopen this issue after providing the needed information! See my comments above.
